<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_MyNextClassDropDown</name>
   <tag></tag>
   <elementGuidId>bb10f8b0-0114-471d-9c68-4512dea78d1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div[2]/div/div[2]/div/app-my-class/div/app-next-class/div/div/span/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-fw fa-chevron-down</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;app-content-body&quot;]/div[@class=&quot;hbox hbox-auto-xs hbox-auto-sm&quot;]/div[@class=&quot;col wrapper-md&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/app-my-class[1]/div[@class=&quot;row&quot;]/app-next-class[@class=&quot;col-md-12 col-sm-12&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-heading clearfix bg-green&quot;]/span[@class=&quot;pull-right&quot;]/a[1]/i[@class=&quot;fa fa-fw fa-chevron-down&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[2]/div/div[2]/div/app-my-class/div/app-next-class/div/div/span/a/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a/i</value>
   </webElementXpaths>
</WebElementEntity>
